### ISSUE TITLE
Decoding fragment fails on double bond, [possible bug]?

### ISSUE THREAD

**Issue by hjuinj** [datamol-io/safe#22]
I noticed that if the slicer (in this case BRICS) breaks double bonds, the resulting fragment cannot be properly decoded. 

Using such a molecule and following the documentation:
```
import safe as sf

safe_str = sf.encode("C(=C/c1ccccc1)\CCc1ccccc1", canonical=True)
print(safe_str)

safe_fragment = safe_str.split(".")
sf.decode(safe_fragment[0], as_mol=True)
```
I get: `SAFEDecodeError: Failed to decode C(=2)c1ccccc1`

I think the more appropriate output might be `C(=[*])c1ccccc1`??

**Comment by maclandrol** [comment]
Hi @hjuinj , 

This one is indeed a strange case, thanks for bringing it up. I would have liked to say the issue is with BRICS as a general slicing algorithm, but it's definitely not that xD.

In your example, the encoded safe strings is not even recognized by the  RDKit SMILES parser which was weird.

```python
import safe as sf
import datamol as dm

input_sm = "C(=C/c1ccccc1)\CCc1ccccc1"
safe_str = sf.encode(input_sm, canonical=True)

print(safe_str) 
# C(=2)c1ccccc1.c13ccccc1.C(=2)CC3
dm.to_mol(safe_str)
#[17:32:50] SMILES Parse Error: syntax error while parsing: C(=2)c1ccccc1.c13ccccc1.C(=2)CC3
#[17:32:50] SMILES Parse Error: Failed parsing SMILES 'C(=2)c1ccccc1.c13ccccc1.C(=2)CC3' for input: 'C(=2)c1ccccc1.c13ccccc1.C(=2)CC3'

```

I put the same string into [marvinjs](https://marvinjs-demo.chemaxon.com/) and it works, although the steroisomers typing does not seem exact.

<img width="650" alt="image" src="https://github.com/datamol-io/safe/assets/5290110/0fae7232-8b51-462e-821b-68b507052043">

Forcing the encoder to not break any double bonds, works so it's as you say about breaking double bonds.

```python
safe_str = sf.encode(input_sm, canonical=True, constraints=[dm.to_mol("C=C")])
print(safe_str)
# C(=C/c1ccccc1)\CC2.c12ccccc1

decoded_str = sf.decode(safe_str, as_mol=False)
print(decoded_str)
# C(=C/c1ccccc1)\\CCc1ccccc1

```
![image](https://github.com/datamol-io/safe/assets/5290110/dcfbe10a-ebab-4e7d-855b-5cc05d217ee2)

**I notice that it has nothing to do with stereochemistry**

The following still fails and even simpler example like this `CCC=CCCC` don't work. 

```python
m = dm.to_mol(input_sm)
no_stereo = dm.remove_stereochemistry(m)
stereo_iso = dm.enumerate_stereoisomers(no_stereo)
mols = [m, no_stereo] + stereo_iso
valid_mols = []
for x in mols:
    safe_str = sf.encode(x, canonical=True)
    valid_mols.append(sf.decode(safe_str, as_mol=False))
valid_mols # [None, None, None, None]
```

It's possible that the RDKit parser is not respecting the full SMILES specification. This could be worth bringing up to them. For now I believe the issue is how parentheses around attachment points only are handled by RDKit (RDKit parser already does not support parenthesis around digits only).

Here is a potential fix.

```python

import re
def fix_rdkit_smiles(safe_str):
    """
    Transform the chemical notation by removing the parenthesis around bonds (-, =, @, #), followed by digits
    """
    pattern = r'\(([=-@#]?)(%?\d{1,2})\)'
    replacement = r'\1\2'
    fixed_safe_str = re.sub(pattern, replacement, safe_str)

    return fixed_safe_str
```

```python
import safe as sf

safe_str = sf.encode("C(=C/c1ccccc1)\CCc1ccccc1", canonical=True)
fixed_safe_str = fix_rdkit_smiles(safe_str)
print(fixed_safe_str)

safe_fragment = fixed_safe_str.split(".")
sf.decode(safe_fragment[0], as_mol=True, remove_dummies=False)

```
![image](https://github.com/datamol-io/safe/assets/5290110/3a509d86-4681-41fc-9cf1-68c12a934848)

I will wait to investigate a bit more before making a PR (likely sometime next week). 

Thank you.

**Comment by hjuinj** [comment]
Thank you so much for the investigation @maclandrol, in the case you showed at the end, should the decoder return `C(c1ccccc1)=[*:2]` instead of `C(c1ccccc1)=[*:1]` to preserve the original indexing in the "fragmented smiles" `C(=2)c1ccccc1.c13ccccc1.C(=2)CC3`. This would facilitate associating the correct attachment points amongst the fragments

**Comment by maclandrol** [comment]
> should the decoder return C(c1ccccc1)=[*:2] instead of C(c1ccccc1)=[*:1] to preserve the original indexing in the "fragmented smiles" C(=2)c1ccccc1.c13ccccc1.C(=2)CC3. This would facilitate associating the correct attachment points amongst the fragments

Let me check this. For now there is no mechanism to enforce that information, since in this example, the fragment is decoded without keeping the context about the other fragments. Shouldn't be too hard to add that. 

I will try to make a PR today.
