### ISSUE TITLE
Decoding fragments containing square brackets fail

### ISSUE THREAD

**Issue by hjuinj** [datamol-io/safe#24]
I am using the decoder to decode individual fragments and I notice that if the fragment smiles contain square brackets then the following decoding fails:

```
import safe as sf
import datamol as dm

example_failed = """
O=C(CN1CC[NH2+]CC1)N1CCCCC1
[NH3+]Cc1ccccc1
c1cc2c(cc1[C@@H]1CCC[NH2+]1)OCCO2
"""


safe_obj = sf.SAFEConverter(slicer="brics", require_hs=False)

safe_str = sf.encode("c1cc2c(cc1[C@@H]1CCC[NH2+]1)OCCO2", canonical=True)
 safe_fragment = safe_str.split(".")

  with dm.without_rdkit_log():
      for frag in safe_fragment:
            f = safe_obj.decoder(
                frag,
                as_mol=False,
                canonical=False, 
                fix=True,
                remove_dummies=True,
                remove_added_hs=True,
           )
           if f is None: print(frag)
```

This returns None and I feel this is due to the way square brackets are parsed in the decoder.

Thank you.

**Comment by FNTwin** [comment]
Hi @hjuinj  ,

thanks for bringing it up! It seems that the main issue is the way we are training to find the branch number to attach the fragments.

Right now we are searching for the branch number with this simple regex:
```python
re.findall(r"((?<=%)\d{2})|((?<!%)\d+)", inp)
# c14ccccc1.[NH3+]C4 
# [1, 4, 1, 3, 4] branch numbers and rdkit cannot close the branch 3 as it is from the hydrogen number inside []
``` 

A particular side effect of this issue is that we are going to enumerate the branch numbers and attachment points from the 3 inside the square bracket even if we would have only 2 fragments.
To adress this we need to do a little sanitization of the input in the attachment points procedure `_find_branch_number`, a quick fix is just avoid to find digits inside square brackets:
```python
   @classmethod
   def _find_branch_number(cls, inp: str):
        """Find the branch number and ring closure in the SMILES representation using regexp

        Args:
            inp: input smiles
        """
        inp = re.sub("[\[].*?[\]]","", inp) # ADDITIONAL SANITIZATION
        matching_groups = re.findall(r"((?<=%)\d{2})|((?<!%)\d+)", inp)
       # Rest of the function 
       ...
       return branch_numbers
 
# Now we are creating a more correct safe string and the branch numbers are correct     
# c12ccccc1.[NH3+]C2
#[1, 2, 1, 2]
``` 

Now by running your code:
```python
example_failed = [
"O=C(CN1CC[NH2+]CC1)N1CCCCC1",
"[NH3+]Cc1ccccc1",
"c1cc2c(cc1[C@@H]1CCC[NH2+]1)OCCO2"
]


safe_obj = sf.SAFEConverter(slicer="brics", require_hs=False)

safe_fragment = safe_str.split(".")
frags=[]
with dm.without_rdkit_log():
    for smiles in example_failed:
        safe_str = sf.encode(smiles, canonical=True)
        for frag in safe_str.split("."):
            f = safe_obj.decoder(
                frag,
                as_mol=False,
                canonical=False, 
                fix=True,
                remove_dummies=True,
                remove_added_hs=True,
            )
            if f is not None: 
                print(frag)
                frags.append(dm.to_mol(f))

dm.viz.to_image(frags, n_cols=5, use_svg=False)

#N13CC[NH2+]CC1
#N12CCCCC1
#O=C2C3
#c12ccccc1
#[NH3+]C2
#c1cc2c(cc13)OCCO2
#[C@@H]13CCC[NH2+]1
``` 
<img width="768" alt="image" src="https://github.com/datamol-io/safe/assets/30401800/4b192a7e-406a-45b1-904c-62e6a42b1032">

I will investigate a bit more before doing a PR but if you discover any other problems let us know!
Thank you.

**Comment by hjuinj** [comment]
Thank you so much @FNTwin, will do!

**Comment by maclandrol** [comment]
Thanks @FNTwin. Outside of charges, can you also try to check and cover the cases of 

- isotopes
- atom mapping number ?

I believe that they should all be addressed with removing the content in bracket first, but worth testing.

**Comment by FNTwin** [comment]
I'm adding other tests, good thing that you reminded me of other edge cases! Once I cover all the interesting cases I'll open a PR.
