### ISSUE TITLE
Mol rings and attachment number with multiple rings

### ISSUE THREAD

**Issue by nahhhhhhhhhhhhhhhhhhhhh** [datamol-io/safe#29]
Amazing work guys! Very impressed. 

We had an issue with encode func on the following molecule:

import safe as sf
eh=sf.encode('CC1=CC=C(C=C1)C#CC1=NC=C(C=C1)C(F)(F)F')
print(eh)
#Cc1ccc(C#Cc2ccc2cn2)cc1.C2(F)(F)F
#expecting:
#Cc1ccc(C#Cc2ccc3cn2)cc1.C3(F)(F)F
sf.to_image('Cc1ccc(C#Cc2ccc3cn2)cc1.C3(F)(F)F')

Thank you!

**Comment by maclandrol** [comment]
Hi @nahhhhhhhhhhhhhhhhhhhhh, 

Thanks for the feedback. 

The main reason this SMILES is failing is because it's not standardized properly, which leads to misleading branching points. 

We could deal with it by forcing the standardization of input SMILES within SAFE, but I have to think  more carefully about the implication of doing so first.

In the meantime. Even just a single canonicalization of the SMILES would work. 

```python
from rdkit import Chem
smi = "CC1=CC=C(C=C1)C#CC1=NC=C(C=C1)C(F)(F)F"
smi_canon = Chem.CanonSmiles(smi)
print(smi_canon) # Cc1ccc(C#Cc2ccc(C(F)(F)F)cn2)cc1

import safe as sf
eh = sf.encode(smi_canon)
print(eh) # Cc1ccc(C#Cc2ccc3cn2)cc1.C3(F)(F)F

sf.to_image(eh)
```

Alternatively standardize the mol completely 
```python
import datamol as dm
smi = "CC1=CC=C(C=C1)C#CC1=NC=C(C=C1)C(F)(F)F"
smi_std = dm.standardize_smiles(smi)
print(smi_std) # Cc1ccc(C#Cc2ccc(C(F)(F)F)cn2)cc1

import safe as sf
eh = sf.encode(smi_std)
print(eh) # Cc1ccc(C#Cc2ccc3cn2)cc1.C3(F)(F)F


sf.to_image(eh)
```

**Comment by nahhhhhhhhhhhhhhhhhhhhh** [comment]
Thanks for the speedy reply! We will standardise the mol. Thank you!

**Comment by maclandrol** [comment]
Feel free to close the issue if you are satisfied with the resolution.
