### ISSUE TITLE
[BUG] Max length not always followed

### ISSUE THREAD

**Issue by GabrielMarcus1** [datamol-io/safe#56]
If you use de-novo generation ( I havnt tested on the other techniques) you can get outputs greater than max length specified. I tried it on temperature and for higher temperatures like 1.3 some sequencwes generated were over my max length specified

**Comment by maclandrol** [comment]
Hi @GabrielMarcus1,  the max length parameters is for the max number of tokens and not for the maximum number of characters or atoms. Additionally, it should be interpreted as maximum number of **new tokens** sampled. 

Because of that, you might have sequences that have more "characters" than the requested max length, but the number of tokens should normally be within the range. This is because we are using a BPE-like tokenizer and thus, you might have several characters per tokens (for example: `"[C@@H]"` is a single token). 

Could you check first by re-tokenizing your output and checking the number of tokens that max_length is respected ?
